---
title: "Stock Assessment Graphs"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r sag1, echo=FALSE, fig.height=3, fig.width=3, fig.align='left'}

 library(htmlwidgets)
 library(dplyr)
 library(ggplot2)
 library(gridExtra)
 library(dygraphs)
 library(plotly)
 library(htmltools)
 library(flexdashboard)
 data <- read.csv("Data/hke/hkedata.csv")

 dyBarChart <- function(dygraph) {
  dyPlotter(dygraph = dygraph,
            name = "BarChart",
            path = system.file("examples/plotters/barchart.js",
                               package = "dygraphs"))
}

 catches <- data %>% select(Year, catches)
 catches$catches <- catches[, "catches"]/1000

 dygraph(catches, main = "Catches")%>%
   dyRangeSelector()%>%
   dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2"), drawGrid = FALSE,maxNumberWidth = 4)%>%
   dyAxis("y", label = "Catches in 1000 t")%>%
   dyBarChart()

 
```

### Chart B
```{r sag3, echo = FALSE, fig.height = 3, fig.width = 3, fig.align = "right"}
library(dygraphs)
library(htmlwidgets)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(dygraphs)

dyBarChart <- function(dygraph) {
  dyPlotter(dygraph = dygraph,
            name = "BarChart",
            path = system.file("examples/plotters/barchart.js",
                               package = "dygraphs"))
} 

F <- data %>% select(Year, low_F, F,high_F, FLim, Fpa, FMSY )
 dygraph(F, main = "F") %>%
  dySeries(c("low_F", "F", "high_F"))%>%
   dyLimit(as.numeric(F[, 5]), color = "red")%>%
   dyRangeSelector()%>%
   dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2"),
             drawGrid= FALSE,maxNumberWidth = 4)%>%
   dyAxis("y", label = "F(15-80cm)")

```



Column {data-width=500}
-----------------------------------------------------------------------

### Chart C
```{r sag2echo=FALSE, fig.height=3, fig.width=3, fig.align='left'}

 library(htmlwidgets)
 library(dplyr)
 library(ggplot2)
 library(gridExtra)
 library(dygraphs)
 library(plotly)
 library(htmltools)
 library(flexdashboard)
 data <- read.csv("Data/hke/hkedata.csv")

 dyBarChart <- function(dygraph) {
  dyPlotter(dygraph = dygraph,
            name = "BarChart",
            path = system.file("examples/plotters/barchart.js",
                               package = "dygraphs"))
}
 recruitment<- data %>% select(Year, low_recruitment, recruitment, high_recruitment)

dygraph(recruitment, main = "Recruitment(age 0)") %>%
   dyRangeSelector()%>%
   # dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2"))%>%
   dyAxis("y", label = "Recruitment in millions")%>%
   dyBarChart()

```


### Chart D

```{r sag4echo = FALSE, fig.height = 3, fig.width = 3, fig.align = "right"}
library(dygraphs)
library(htmlwidgets)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(dygraphs)

dyBarChart <- function(dygraph) {
  dyPlotter(dygraph = dygraph,
            name = "BarChart",
            path = system.file("examples/plotters/barchart.js",
                               package = "dygraphs"))
} 

SSB <- data %>% select(Year, low_SSB, SSB,high_SSB, Blim, Bpa, MSYBtrigger)
 dygraph(SSB, main = "SSB") %>%
  dySeries(c("low_SSB", "SSB", "high_SSB"))%>%
   dyLimit(as.numeric(F[, 5]), color = "red")%>%
   dyRangeSelector()%>%
   dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2"),
             drawGrid= FALSE,maxNumberWidth = 4)%>%
   dyAxis("y", label = "SSB in 1000 t")

```


